import type { ShowcaseConfig, VehicleItem } from "./types";

const img = (name: string) => `/images/showcases/aurum-motors/${name}`;

export const vehicles: VehicleItem[] = [
  {
    slug: "cadillac-escalade-premium-luxury",
    name: "Cadillac Escalade Premium Luxury",
    brand: "Cadillac",
    category: "SUV",
    price: "R$ 489.900",
    spec: { year: 2023, mileageKm: 18500, transmission: "Automático", fuel: "Gasolina" },
    image: img("vehicle-cadillac-escalade.jpg"),
    imageAlt: "Cadillac Escalade preto em pátio ao ar livre",
    tag: "Selecionado",
    featured: true,
    description:
      "Unidade único dono, revisões em dia na rede autorizada, interior em couro e pacote Premium Luxury completo.",
    highlights: ["Bancos com ventilação e massagem", "Head-up display", "Suspensão adaptativa", "Som Premium 36 alto-falantes"],
  },
  {
    slug: "mercedes-gle-400-coupe",
    name: "Mercedes-Benz GLE 400 Coupé",
    brand: "Mercedes-Benz",
    category: "SUV",
    price: "R$ 459.900",
    spec: { year: 2022, mileageKm: 24800, transmission: "Automático", fuel: "Gasolina" },
    image: img("vehicle-mercedes-gle-coupe.jpg"),
    imageAlt: "Mercedes-Benz GLE Coupé cinza-grafite estacionado sob árvores",
    tag: "Baixa quilometragem",
    featured: true,
    description: "Segundo dono, histórico completo, rodas AMG e pacote de linha esportiva.",
    highlights: ["Pacote AMG Line", "Bancos esportivos multicontorno", "Suspensão a ar", "Central multimídia MBUX"],
  },
  {
    slug: "bmw-m4-competition",
    name: "BMW M4 Competition",
    brand: "BMW",
    category: "Esportivo",
    price: "R$ 459.900",
    spec: { year: 2023, mileageKm: 12300, transmission: "Automático", fuel: "Gasolina" },
    image: img("vehicle-bmw-m4.jpg"),
    imageAlt: "BMW M4 branco ao entardecer em ambiente envidraçado",
    featured: false,
    description: "Estado de zero km, garantia de fábrica vigente, pacote M Competition completo.",
    highlights: ["Motor 6 cilindros M TwinPower", "Diferencial M autoblocante", "Freios M Carbon Ceramic", "Bancos em couro Merino"],
  },
  {
    slug: "mercedes-c300-amg-line",
    name: "Mercedes-Benz C 300 AMG Line",
    brand: "Mercedes-Benz",
    category: "Sedã",
    price: "R$ 369.900",
    spec: { year: 2022, mileageKm: 21000, transmission: "Automático", fuel: "Híbrido" },
    image: img("vehicle-mercedes-c300.jpg"),
    imageAlt: "Mercedes-Benz Classe C Coupé cinza-grafite em garagem",
    tag: "Híbrido",
    featured: true,
    description: "Motorização híbrida leve, interior MBUX com tela dupla e pacote AMG Line.",
    highlights: ["Bancos multicontorno", "Ambient light 64 cores", "Assistente de faixa", "Piloto automático adaptativo"],
  },
  {
    slug: "mercedes-g500",
    name: "Mercedes-Benz G 500",
    brand: "Mercedes-Benz",
    category: "SUV",
    price: "R$ 419.900",
    spec: { year: 2021, mileageKm: 33500, transmission: "Automático", fuel: "Gasolina" },
    image: img("vehicle-mercedes-g500.jpg"),
    imageAlt: "Mercedes-Benz Classe G cinza-grafite em garagem privada",
    featured: false,
    description: "Design icônico, tração 4x4 reduzida e acabamento interno premium em couro.",
    highlights: ["Tração integral com reduzida", "Bancos aquecidos e ventilados", "Suspensão adaptativa", "Central multimídia MBUX"],
  },
  {
    slug: "bmw-m340i",
    name: "BMW M340i",
    brand: "BMW",
    category: "Sedã",
    price: "R$ 389.900",
    spec: { year: 2023, mileageKm: 9800, transmission: "Automático", fuel: "Gasolina" },
    image: img("vehicle-bmw-m340i.jpg"),
    imageAlt: "BMW M340i azul em rua residencial ao entardecer",
    tag: "Alta performance",
    featured: true,
    description: "Motor 6 cilindros M Performance, escape esportivo e freios M Sport.",
    highlights: ["0-100 km/h em 4.4s", "Diferencial autoblocante", "Bancos M Sport", "Harman Kardon"],
  },
  {
    slug: "audi-r8-coupe",
    name: "Audi R8 Coupé",
    brand: "Audi",
    category: "Esportivo",
    price: "R$ 459.900",
    spec: { year: 2022, mileageKm: 15200, transmission: "Automático", fuel: "Gasolina" },
    image: img("vehicle-audi-r8.jpg"),
    imageAlt: "Audi R8 vermelho ao entardecer com montanhas ao fundo",
    tag: "Alta performance",
    featured: false,
    description: "V10 aspirado, tração quattro e acabamento interno em couro e Alcantara.",
    highlights: ["Motor V10 5.2 FSI", "Tração quattro", "Freios cerâmicos", "Bancos esportivos em Alcantara"],
  },
  {
    slug: "ram-1500-trx",
    name: "RAM 1500 TRX",
    brand: "RAM",
    category: "Picape",
    price: "R$ 449.900",
    spec: { year: 2023, mileageKm: 15400, transmission: "Automático", fuel: "Gasolina" },
    image: img("vehicle-ram-1500-trx.jpg"),
    imageAlt: "RAM 1500 TRX prata ao entardecer em rua residencial",
    featured: false,
    description: "Suspensão off-road, motor V8 supercharged e pacote TRX completo.",
    highlights: ["Motor V8 6.2 supercharged", "Suspensão off-road Bilstein", "Tração 4x4", "Central multimídia 12\""],
  },
];

export const aurumMotorsConfig: ShowcaseConfig = {
  slug: "aurum-motors",
  primaryCtaHref: "/modelos/aurum-motors/contato",
  company: {
    name: "Aurum Motors",
    shortName: "Aurum",
    segment: "Concessionária de seminovos premium",
    slogan: "Curadoria acima da média.",
    description:
      "Concessionária fictícia, criada como modelo demonstrativo. Loja premium de veículos seminovos selecionados, com foco em curadoria, procedência e experiência de compra.",
  },
  theme: {
    surface: "#131211",
    surfaceAlt: "#1c1a18",
    ink: "#f2ede4",
    inkMuted: "#a89e8f",
    primary: "#b3843c",
    primaryInk: "#15130f",
    accent: "#d9b26a",
    border: "#332e27",
    fontHeading: "'Bricolage Grotesque Variable', system-ui, sans-serif",
    fontBody: "'Inter Variable', system-ui, sans-serif",
    radiusCard: "0.75rem",
  },
  nav: [
    { label: "Início", href: "/modelos/aurum-motors" },
    { label: "Estoque", href: "/modelos/aurum-motors/estoque" },
    { label: "Diferenciais", href: "/modelos/aurum-motors/#diferenciais" },
    { label: "Financiamento", href: "/modelos/aurum-motors/financiamento" },
    { label: "Contato", href: "/modelos/aurum-motors/contato" },
  ],
  seo: {
    title: "Aurum Motors — Seminovos premium selecionados (modelo demonstrativo)",
    description:
      "Modelo demonstrativo de concessionária premium de seminovos, com estoque selecionado, financiamento e agendamento de test-drive. Projeto fictício da CronosStart.",
    ogImage: "/images/og/aurum-motors.png",
    ogImageAlt: "Aurum Motors — modelo demonstrativo CronosStart",
  },
  hero: {
    variant: "centered",
    eyebrow: "Curadoria automotiva",
    headline: "Cada veículo aqui passou por um processo",
    highlight: "que a maioria das lojas nem tenta.",
    subheadline:
      "A Aurum seleciona, inspeciona e prepara cada unidade do estoque a fundo — para que a única decisão que reste a você seja qual dirigir primeiro.",
    ctaPrimaryLabel: "Agendar test-drive",
    ctaSecondaryLabel: "Ver estoque completo",
  },
  vehicleSearch: {
    categories: ["Todas", "SUV", "Sedã", "Esportivo", "Picape"],
    priceRanges: ["Qualquer valor", "Até R$ 300 mil", "R$ 300 a 400 mil", "Acima de R$ 400 mil"],
    brands: ["Todas as marcas", "BMW", "Audi", "Mercedes-Benz", "Cadillac", "RAM"],
  },
  vehicles,
  dealerHighlights: [
    {
      title: "Curadoria rigorosa",
      description: "Menos de 1 em cada 10 veículos avaliados chega a entrar no nosso estoque.",
      icon: "shield-check",
    },
    {
      title: "Procedência garantida",
      description: "Histórico completo verificado, sem sinistro estrutural e com laudo cautelar.",
      icon: "file-check",
    },
    {
      title: "Revisão completa",
      description: "Cada unidade passa por mais de 120 itens de inspeção antes de ir à loja.",
      icon: "tool",
    },
    {
      title: "Garantia estendida",
      description: "Cobertura adicional demonstrativa de até 12 meses em itens de motor e câmbio.",
      icon: "key",
    },
  ],
  tradeIn: {
    eyebrow: "Seu usado na troca",
    title: "Avalie seu carro sem sair de casa",
    description:
      "Envie os dados do seu veículo atual e receba uma proposta de avaliação demonstrativa para usar como entrada na troca.",
    steps: [
      "Envie marca, modelo, ano e quilometragem do seu veículo",
      "Receba uma avaliação preliminar em até 24h (demonstrativo)",
      "Use o valor avaliado como entrada em qualquer veículo do estoque",
    ],
    ctaLabel: "Avaliar meu veículo",
  },
  financing: {
    eyebrow: "Financiamento",
    title: "Condições pensadas para fechar negócio",
    description: "Simulação demonstrativa — condições finais dependem de análise de crédito e do veículo escolhido.",
    bullets: [
      "Aprovação em até 24h (demonstrativo)",
      "Entrada facilitada a partir de 20%",
      "Parcelamento em até 60x",
      "Parceria com os principais bancos e financeiras",
    ],
    plans: [
      { label: "À vista", description: "Condição especial para pagamento integral na retirada." },
      { label: "Financiado", description: "Entrada facilitada e parcelas que cabem no seu orçamento." },
      { label: "Consórcio", description: "Modalidade sem juros, ideal para planejar a troca com calma." },
    ],
    ctaLabel: "Simular financiamento",
  },
  process: [
    { title: "Escolha seu veículo", description: "Navegue pelo estoque selecionado ou fale com um consultor." },
    { title: "Agende um test-drive", description: "Marque um horário e sinta o carro antes de decidir." },
    { title: "Avaliação e negociação", description: "Avalie seu usado e negocie condições com transparência." },
    { title: "Documentação assistida", description: "Cuidamos da parte burocrática com você, passo a passo." },
    { title: "Retirada do veículo", description: "Vistoria final, entrega revisada e boas-vindas à Aurum." },
  ],
  testimonials: [
    {
      quote:
        "Comprei um SUV com a Aurum e a diferença de cuidado com o carro é visível. Recebi um veículo revisado de verdade, não só lavado.",
      author: "Rafael Monteiro",
      role: "Cliente Aurum",
      segment: "Troca de SUV",
      result: "Financiamento aprovado em 1 dia",
      rating: 5,
    },
    {
      quote:
        "Avaliaram meu usado no mesmo dia e o valor entrou como entrada sem complicação. Processo bem mais rápido do que eu esperava.",
      author: "Camila Duarte",
      role: "Cliente Aurum",
      segment: "Troca com avaliação",
      result: "Negócio fechado em 3 dias",
      rating: 5,
    },
    {
      quote:
        "O que me convenceu foi a transparência do laudo do veículo. Deu segurança pra fechar negócio à distância.",
      author: "Eduardo Prado",
      role: "Cliente Aurum",
      segment: "Compra à vista",
      result: "Retirada agendada em 48h",
      rating: 4,
    },
  ],
  contactCta: {
    title: "Vamos agendar seu test-drive?",
    description: "Escolha o veículo, o dia e o horário — nossa equipe confirma rapidinho.",
    buttonLabel: "Agendar test-drive",
  },
  location: {
    addressLine: "Av. Engenheiro Luís Carlos Berrini, 1500 — Brooklin, São Paulo/SP",
    mapNote: "Mapa ilustrativo",
    hoursLines: [
      { day: "Segunda a sexta", hours: "9h–19h" },
      { day: "Sábado", hours: "9h–15h" },
      { day: "Domingo", hours: "Fechado" },
    ],
  },
  contact: {
    whatsappNumber: "5511977770000",
    whatsappMessage: "Olá! Gostaria de agendar um test-drive na Aurum Motors.",
    email: "contato@aurummotors-demo.com.br",
    phone: "(11) 4000-7700",
    city: "São Paulo",
    state: "SP",
    hours: "Segunda a sábado, 9h às 19h",
  },
  sections: {
    vehicleSearch: true,
    featuredVehicles: true,
    dealerHighlights: true,
    tradeIn: true,
    financing: true,
    process: true,
    testimonials: true,
    location: true,
  },
};
