import type { ShowcaseConfig } from "./types";

export const imobiliariaConfig: ShowcaseConfig = {
  slug: "imobiliaria",
  primaryCtaHref: "#encontrar",
  company: {
    name: "Vértice Imóveis",
    shortName: "Vértice",
    segment: "Imobiliária",
    slogan: "O ponto certo entre o imóvel e a decisão certa.",
    description:
      "Imobiliária fictícia, criada como modelo demonstrativo. Curadoria de imóveis para compra e aluguel, com atendimento acompanhado do primeiro contato à entrega das chaves.",
  },
  theme: {
    surface: "#faf8f5",
    surfaceAlt: "#f0e9dc",
    ink: "#211d18",
    inkMuted: "#6b6255",
    primary: "#221e19",
    primaryInk: "#ffffff",
    accent: "#b8873e",
    border: "#e4dbc9",
    fontHeading: "'Manrope Variable', system-ui, sans-serif",
    fontBody: "'Inter Variable', system-ui, sans-serif",
    radiusCard: "1rem",
  },
  nav: [
    { label: "Início", href: "#" },
    { label: "Imóveis", href: "#imoveis" },
    { label: "Comprar", href: "#imoveis" },
    { label: "Alugar", href: "#imoveis" },
    { label: "Sobre", href: "#sobre" },
    { label: "Contato", href: "#encontrar" },
  ],
  seo: {
    title: "Vértice Imóveis — Compra, aluguel e atendimento acompanhado (modelo demonstrativo)",
    description:
      "Modelo demonstrativo de site para imobiliárias, com busca de imóveis, destaques, processo de atendimento e corretores. Projeto fictício da CronosStart.",
    ogImage: "/images/og/imobiliaria.png",
    ogImageAlt: "Vértice Imóveis — modelo demonstrativo CronosStart",
  },
  hero: {
    variant: "centered",
    eyebrow: "Compra e aluguel com acompanhamento",
    headline: "Encontre o imóvel certo, com quem entende",
    highlight: "cada detalhe da negociação.",
    subheadline:
      "A Vértice reúne imóveis selecionados para compra e aluguel, com corretores dedicados do primeiro contato à entrega das chaves.",
    ctaPrimaryLabel: "Encontrar meu imóvel",
  },
  process: [
    {
      title: "Entendimento do perfil",
      description: "Conhecemos o que você busca: finalidade, região, orçamento e prazo.",
    },
    {
      title: "Seleção de imóveis",
      description: "Filtramos opções compatíveis com o seu perfil, sem visitas perdidas.",
    },
    {
      title: "Visitas acompanhadas",
      description: "Um corretor dedicado acompanha cada visita, com informações claras.",
    },
    {
      title: "Fechamento assistido",
      description: "Documentação, negociação e entrega de chaves com suporte completo.",
    },
  ],
  explore: {
    eyebrow: "Explore",
    title: "Filtre por tipo de imóvel ou por região",
    description: "Uma prévia de como os visitantes podem navegar pelo catálogo — apenas demonstrativo nesta fase.",
    types: ["Apartamento", "Casa", "Cobertura", "Comercial", "Terreno"],
    regions: ["Centro", "Zona Sul", "Zona Norte", "Zona Leste", "Zona Oeste"],
  },
  about: {
    eyebrow: "Sobre a Vértice",
    title: "Uma curadoria imobiliária, não uma vitrine de anúncios",
    paragraphs: [
      "A Vértice nasceu para simplificar a compra e o aluguel de imóveis, com uma curadoria criteriosa e corretores que acompanham cada etapa da negociação.",
      "Menos anúncios repetidos, mais imóveis que realmente combinam com o que você procura.",
    ],
    stats: [
      { label: "Imóveis na carteira", value: "320+" },
      { label: "Anos de atuação", value: "9" },
      { label: "Negociações fechadas", value: "1.100+" },
      { label: "Tempo médio de resposta", value: "2h" },
    ],
    statsNote: "Números ilustrativos, usados apenas para compor esta demonstração.",
  },
  team: [
    {
      name: "Marcos Tavares",
      role: "Especialista em Zona Sul",
      avatar: "/images/showcases/imobiliaria/corretores/marcos-tavares.jpg",
      avatarAlt: "Retrato profissional de Marcos Tavares, corretor demonstrativo",
    },
    {
      name: "Bianca Souza",
      role: "Imóveis comerciais",
      avatar: "/images/showcases/imobiliaria/corretores/bianca-souza.jpg",
      avatarAlt: "Retrato profissional de Bianca Souza, corretora demonstrativa",
    },
    {
      name: "Renato Lima",
      role: "Alto padrão e coberturas",
      avatar: "/images/showcases/imobiliaria/corretores/renato-lima.jpg",
      avatarAlt: "Retrato profissional de Renato Lima, corretor demonstrativo",
    },
  ],
  properties: [
    {
      title: "Apartamento 3 quartos — Zona Sul",
      location: "Zona Sul, São Paulo/SP",
      price: "R$ 890.000",
      operation: "Venda",
      image: "/images/showcases/imobiliaria/apartamento-3-quartos.jpg",
      imageAlt: "Sala de estar integrada de apartamento moderno, com sofá verde e piso de madeira",
      bedrooms: 3,
      area: "98 m²",
      parking: 2,
    },
    {
      title: "Casa térrea com quintal",
      location: "Zona Oeste, São Paulo/SP",
      price: "R$ 3.200/mês",
      operation: "Aluguel",
      image: "/images/showcases/imobiliaria/casa-terrea-quintal.jpg",
      imageAlt: "Casa térrea com quintal amplo, área externa e jardim",
      bedrooms: 4,
      area: "180 m²",
      parking: 3,
    },
    {
      title: "Sala comercial no Centro",
      location: "Centro, São Paulo/SP",
      price: "R$ 420.000",
      operation: "Venda",
      image: "/images/showcases/imobiliaria/sala-comercial-centro.jpg",
      imageAlt: "Fachada de edifício comercial moderno no início da noite",
      area: "45 m²",
      parking: 1,
    },
    {
      title: "Cobertura duplex",
      location: "Zona Sul, São Paulo/SP",
      price: "R$ 1.750.000",
      operation: "Venda",
      image: "/images/showcases/imobiliaria/cobertura-duplex.jpg",
      imageAlt: "Sala de estar de cobertura de alto padrão, com lustre e piano de cauda",
      bedrooms: 4,
      area: "220 m²",
      parking: 3,
    },
    {
      title: "Apartamento 2 quartos mobiliado",
      location: "Zona Leste, São Paulo/SP",
      price: "R$ 2.400/mês",
      operation: "Aluguel",
      image: "/images/showcases/imobiliaria/apartamento-2-quartos-mobiliado.jpg",
      imageAlt: "Quarto mobiliado com cômoda de madeira, espelho redondo e planta decorativa",
      bedrooms: 2,
      area: "62 m²",
      parking: 1,
    },
    {
      title: "Terreno para construção",
      location: "Zona Norte, São Paulo/SP",
      price: "R$ 560.000",
      operation: "Venda",
      image: "/images/showcases/imobiliaria/terreno-construcao.jpg",
      imageAlt: "Vista aérea de terreno urbano vazio, cercado por árvores e via pública",
      area: "360 m²",
      note: "Documentação regularizada",
    },
  ],
  testimonials: [
    {
      quote:
        "Depois de meses vendo anúncios repetidos em outros sites, a Vértice apresentou 3 opções que realmente combinavam com o que eu procurava — fechamos em duas semanas.",
      author: "Fernanda Diniz",
      role: "Cliente Vértice",
      segment: "Compra residencial",
      result: "Negociação fechada em 2 semanas",
    },
    {
      quote: "O corretor acompanhou cada visita e nos avisou sobre um problema na documentação antes de assinarmos.",
      author: "Hugo Martins",
      role: "Cliente Vértice",
      segment: "Aluguel residencial",
      result: "Documentação revisada a tempo",
    },
    {
      quote: "Encontramos a sala comercial certa em menos visitas do que esperávamos.",
      author: "Carla Nogueira",
      role: "Cliente Vértice",
      segment: "Locação comercial",
      result: "Menos visitas, mais acerto",
    },
  ],
  contactCta: {
    title: "Vamos encontrar o imóvel ideal?",
    description: "Conte o que você procura e um corretor entra em contato com opções compatíveis com seu perfil.",
    buttonLabel: "Encontrar meu imóvel",
  },
  contact: {
    whatsappNumber: "5511977770000",
    whatsappMessage: "Olá! Gostaria de ajuda para encontrar um imóvel.",
    email: "contato@verticeimoveis-demo.com.br",
    phone: "(11) 4000-2300",
    city: "São Paulo",
    state: "SP",
    hours: "Seg. a sáb., 9h às 18h",
    instagram: "#",
    facebook: "#",
    linkedin: "#",
  },
  propertySearch: {
    operationOptions: ["Comprar", "Alugar"],
    regions: ["Centro", "Zona Sul", "Zona Norte", "Zona Leste", "Zona Oeste"],
    propertyTypes: ["Apartamento", "Casa", "Cobertura", "Comercial", "Terreno"],
  },
  propertyLeadForm: {
    operationOptions: ["Comprar", "Alugar"],
    propertyTypes: ["Apartamento", "Casa", "Cobertura", "Comercial", "Terreno"],
    regions: ["Centro", "Zona Sul", "Zona Norte", "Zona Leste", "Zona Oeste"],
  },
  sections: {
    about: true,
    process: true,
    testimonials: true,
    team: true,
    explore: true,
  },
};
